#' Code to create figure 2.
#' 
#'

# source("04_main_figures/02_multitrait_GWA/SNP_heritability.Rmd")
source("04_main_figures/02_multitrait_GWA/necrosis-manhattan-plot.R")
# Import pseudoheritabilities and var. expained by the top SNP
# generated by pseudoheritabiliy.Rmd
h2 <- read_csv("04_main_figures/02_multitrait_GWA/output/pseudoheritabiliy.csv")

pd <- position_dodge(0.4)

pseudoheritability <- h2 %>%
  filter(component != 'geno') %>% 
  mutate(
    Virus = ifelse(grepl("*Anc*", trait), "Ancestral", "Evolved"),
    `Top SNP` = ifelse(component == "h2_full", "Without", "With"),
    trait = str_extract(trait, "^[^_]+"),
    trait = ifelse(trait == "SYM", "Symptoms", trait)
  ) %>% 
  ggplot(aes(x = trait, y = Estimate, group=paste(Virus, component), colour = Virus, shape = `Top SNP`)) +
  geom_point(position = pd) +
  geom_errorbar(aes(
    ymin = Estimate - SE,
    ymax =  Estimate + SE
  ),
  position = pd, width = 0.1) +
  labs(
    x = "",
    y = "SNP heritability"
  ) +
  theme(
    axis.title.x = element_blank(),
    legend.position = "top"
    ) +
  scale_x_discrete(
    labels =
      c("AUDPS", "Infectivity", "Necrosis", "Severity of\nsymptoms")
  ) +
  theme_classic()

png(
  filename = "04_main_figures/02_multitrait_GWA/fig2.png",
  width = 12, height = 15, units = 'cm', res = 300)
# Plot the MH plot and the zoom in together
ggpubr::ggarrange(
  pseudoheritability, necrosis_manh,
  nrow=2, labels = "AUTO", heights = c(2,3)
)
dev.off()
