#' Code to create figure 2.
#' 
#'

source("04_main_figures/02_multitrait_GWA/SNP_heritability.Rmd")
source("04_main_figures/02_multitrait_GWA/necrosis-manhattan-plot.R")
# Import pseudoheritabilities and var. expained by the top SNP
# generated by pseudoheritabiliy.Rmd
h2 <- read_csv("04_main_figures/02_multitrait_GWA/")

pd <- position_dodge(0.4)

pseudoheritability <- h2 %>% 
  filter(component != 'geno') %>% 
  mutate(
    Virus = ifelse(grepl("*Anc*", trait), "TuMV-Anc", "TuMV-Evo"),
    `Top SNP` = ifelse(component == "h2_full", "Without", "With"),
    trait = str_extract(trait, "^[^_]+"),
    trait = ifelse(trait == "SYM", "Symptoms", trait)
  ) %>% 
  ggplot(aes(x = trait, y = Estimate, group=paste(Virus, component), colour = Virus, shape = `Top SNP`)) +
  geom_point(position = pd) +
  # geom_col() + 
  geom_errorbar(aes(
    ymin = Estimate - SE,
    ymax =  Estimate + SE
  ),
  position = pd, width = 0.1) +
  labs(
    x = "Trait",
    y = "SNP heritability"
  ) +
  theme(legend.position = "top") +
  theme_classic()

png(
  filename = "008_manuscript/00_old_versions/211102_plos_genetics/figures/fig2.png",
  width = 12, height = 20, units = 'cm', res = 600)
# Plot the MH plot and the zoom in together
ggpubr::ggarrange(
  pseudoheritability, necrosis_manh, zoomed_manh,
  nrow=3, labels = "AUTO"
)
dev.off()
