#' Code to create figure 2.

source("05_figures/fig2/necrosis-manhattan-plot.R")
source("05_figures/fig2/relative_risk/relative_risk.R")

p1 <- ggarrange(plotlist = manh, labels = LETTERS[1:4])
p2 <- ggarrange(plotlist = relrisk, legend = "none" , labels = LETTERS[5:6], ncol=2)

png(
  filename = "05_figures/fig2/fig2.png",
  width = 18, height = 15, units = 'cm', res = 300
  )
  ggarrange( p1, p2, nrow = 2 , heights = c(3,2) )
  # ggarrange( p1, p2, ncol = 2 , widths = c(2,1) )
dev.off()

# # Import pseudoheritabilities and var. expained by the top SNP
# # generated by pseudoheritabiliy.Rmd
# h2 <- read_csv("04_main_figures/02_multitrait_GWA/output/pseudoheritabiliy.csv")
# 
# pd <- position_dodge(0.4)
# 
# pseudoheritability <- h2 %>%
#   filter(component != 'geno') %>% 
#   mutate(
#     Virus = ifelse(grepl("*Anc*", trait), "Ancestral", "Evolved"),
#     `Top SNP` = ifelse(component == "h2_full", "Without", "With"),
#     trait = str_extract(trait, "^[^_]+"),
#     trait = ifelse(trait == "SYM", "Symptoms", trait)
#   ) %>% 
#   ggplot(aes(x = trait, y = Estimate, group=paste(Virus, component), colour = Virus, shape = `Top SNP`)) +
#   geom_point(position = pd) +
#   geom_errorbar(aes(
#     ymin = Estimate - SE,
#     ymax =  Estimate + SE
#   ),
#   position = pd, width = 0.1) +
#   labs(
#     x = "",
#     y = "SNP heritability"
#   ) +
#   theme(
#     axis.title.x = element_blank(),
#     legend.position = "top"
#     ) +
#   scale_x_discrete(
#     labels =
#       c("AUDPS", "Infectivity", "Necrosis", "Severity of\nsymptoms")
#   ) +
#   theme_classic()
# 

