# Import pseudoheritabilities and var. expained by the top SNP
# generated by 04_analyses/01_snp_heritability/SNP_heritability.Rmd
h2 <- read_csv("04_analyses/01_snp_heritability/snp_heritability.csv", col_types = 'ccdd')

pd <- position_dodge(0.2)

snp_heritability <- h2 %>%
  mutate(
    Virus = ifelse(grepl("*Anc*", trait), "Ancestral", "Evolved"),
    trait = str_extract(trait, "^[^_]+"),
    trait = ifelse(trait == "SYM", "Symptoms", trait)
  ) %>%
  ggplot(aes(x = trait, y = Estimate, group=paste(Virus, component), colour = Virus)) +
  geom_point(position = pd) +
  geom_errorbar(aes(
    ymin = Estimate - SE,
    ymax =  Estimate + SE
  ),
  position = pd, width = 0.1) +
  labs(
    x = "",
    y = "SNP heritability"
  ) +
  theme_bw() +
  theme(
    axis.title.x = element_blank(),
    axis.text.x = element_text(angle = 45, hjust=1),
    legend.position = "top",
    legend.title = element_blank()
  ) +
  lims(
    y = c(0,0.6)
  ) +
  scale_x_discrete(
    labels =
      c("AUDPS", "Infectivity", "Necrosis", "Severity of\nsymptoms")
  )
